version: '3'
services:
  cassandra:
    build:
      context: cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  annotator:
    image: annotator_supreme
    volumes:
    - static-data:/code/annotator_supreme/static
    depends_on:
    - cassandra
    environment:
    - CLUSTER_IP=cassandra
    - PYTHONUNBUFFERED=1
    
  nginx:
    build:
      context: nginx
    depends_on:
    - annotator
    volumes:
    - static-data:/code/annotator_supreme/static

volumes:
  static-data:
  
