# -*- org-export-babel-evaluate: t; org-link-file-path-type: relative;-*-
#+TITLE: Annotator Supreme
#+LANGUAGE: en 
#+STARTUP: indent
#+STARTUP: logdrawer hideblocks
#+SEQ_TODO: TODO INPROGRESS(i) | DONE DEFERRED(@) CANCELED(@)
#+TAGS: ignore(i) DEPRECATED(d) noexport(n) export(e)
#+OPTIONS: ^:{} H:3 author:nil todo:nil tags:nil
#+PROPERTY: header-args :cache no :eval never-export

A server to annotate and provide computer vision datasets

* Table of Contents                                            :noexport:TOC:
- [[#getting-started][Getting Started]]
  - [[#running-cassandra-db-in-a-docker-container-recomended][Running cassandra db in a docker container (recomended)]]
  - [[#annotator-supreme-in-docker-container][Annotator Supreme in docker container]]
- [[#extra][Extra]]
  - [[#connecting-to-a-local-cassandra-database][Connecting to a local Cassandra database]]

* Getting Started  

Supreme annotator uses a Cassandra database to store the datasets.

** Running cassandra db in a docker container (recomended) 

Get the cassandra docker ( [[https://hub.docker.com/_/cassandra/]] )

#+begin_src sh :results output :exports code
docker pull cassandra 
#+end_src

#+RESULTS:
: Using default tag: latest
: latest: Pulling from library/cassandra
: Digest: sha256:afe579efbad590ac59992b2984d9010184e2f5c1e24e5f1107dde7dd74fd7913
: Status: Image is up to date for cassandra:latest

Run the cassandra container publishing its exposed ports to localhost. 
#+begin_src sh :results output :exports code
docker run -d --name cassandraDB -p 7000:7000 -p 7001:7001 -p 7199:7199 -p 9042:9042 cassandra:latest
#+end_src

#+RESULTS:

** Annotator Supreme in docker container

*** Build the annotator

#+begin_src sh :results output :exports code
docker build -t annotator_supreme -f Dockerfile .
#+end_src

#+RESULTS:
#+begin_example
Sending build context to Docker daemon  49.32MB
Step 1/12 : FROM meerkatcvonpremise/meerkat_base:latest
 ---> ff041dc8c125
Step 2/12 : ADD requirements.txt /code/
 ---> Using cache
 ---> ce7b95ee5700
Step 3/12 : RUN pip3 install pip --upgrade
 ---> Using cache
 ---> 2f1f1f77859d
Step 4/12 : RUN pip3 install -r /code/requirements.txt
 ---> Using cache
 ---> 611de72d56de
Step 5/12 : ADD server /code/server
 ---> Using cache
 ---> c077063939ef
Step 6/12 : ADD annotator_supreme/ /code/annotator_supreme
 ---> Using cache
 ---> f02469ca54ec
Step 7/12 : ADD run_api.py /code/
 ---> Using cache
 ---> de1df25e587b
Step 8/12 : WORKDIR /code
 ---> Using cache
 ---> a3e38e8926ab
Step 9/12 : RUN cp server/nginx.conf /usr/local/nginx/conf/nginx.conf
 ---> Using cache
 ---> f1622bc0bcbd
Step 10/12 : RUN ln -sf /dev/stdout /usr/local/nginx/logs/access.log
 ---> Using cache
 ---> e2ac8b55f60b
Step 11/12 : RUN ln -sf /dev/stderr /usr/local/nginx/logs/error.log
 ---> Using cache
 ---> 266c2bf21716
Step 12/12 : CMD supervisord -c server/supervisord.conf
 ---> Using cache
 ---> e023f82d8879
Successfully built e023f82d8879
Successfully tagged annotator_supreme:latest
#+end_example

*** Starting the container for annotating 

Get the IP address of the running cassandra container.
#+NAME: clusterIP
#+begin_src sh :results output :exports both 
CLUSTER_IP=$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' cassandraDB)
echo $CLUSTER_IP
#+end_src

#+RESULTS: clusterIP
: 172.17.0.2

Start the annotator container passing the IP of the other container. 
#+begin_src sh :results output :exports code :var CLUSTER_IP=clusterIP
docker run -d --env CLUSTER_IP=$CLUSTER_IP -p 80:80 \
       --add-host=cassandraDB:$CLUSTER_IP annotator_supreme
#+end_src

#+RESULTS:
: 789551a62e2b203b1ca698f7db8331bbbef07e1a11f91b11bd5b8dc4e348cb30

If everything works as expected annotator is serving at [[http://localhost/annotator-supreme/]]

*** Starting for Development 

You can mount a volume with your code directory into the container.
By appending the =bash= command to the docker run, neither the application nor the nginx webserver will start.
#+begin_src sh :results output :exports code :var CLUSTER_IP=clusterIP
docker run -itd --name AnnotatorDEV \
       -v $HOME/Projects/annotator-supreme:/home \
       --env CLUSTER_IP=$CLUSTER_IP \
       -p 80:80 \
       --add-host=cassandraDB:$CLUSTER_IP annotator_supreme bash
#+end_src

#+RESULTS:
: 1b8621841d271464ee7c27ff79c920617904089fe3218d45478dd46bc52f0bb5

Start nginx manually and the annotator api manually
#+begin_src sh :results output :exports both
root@1b8621841d27:/home# /usr/local/nginx/sbin/nginx & python3 run_api.py
#+end_src


* Extra
** Connecting to a local Cassandra database

Alternatively it is possible to run connect to a cassandra database running natively on the host.

To connect the app to a Cassandra database running you have to run the container on the =host= network [[https://docs.docker.com/engine/reference/run/#network-settings]]

#+begin_src sh :results output :exports both
docker run -d --network="host" annotator_supreme
#+end_src

